project:
  type: website
  
website:
  favicon: 10mapz.ico
  title: "<span class='site-subtitle'>Martijn</span> Tennekes"
  navbar:
    logo: images/10mapz3.png
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: gallery.qmd
        text: Gallery
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

resources:
  - pop64_2025.html
  - downloads/**
