---
title: "Publications"
toc: false # disable table of contents for this page (if applicable)
about: 
  template: jolla 
  links: # create buttons
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/martijn-tennekes-387202125/
      target: _blank # opens link in a new browser tab
    - icon: github
      text: GitHub
      href: https://github.com/mtennekes
      target: _blank 
    - icon: envelope
      text: Email
      href: mailto:mtennekes@gmail.com
---


:::{.justify-text}

## 2025

<span class = "paper">Stoel, R., Snijkers, G., Tennekes, M., Jonge, E. de, Krol, N., Puts, M. J. H., Meertens, V., Hoogendoorn, D., Bongers, N., Boer, D. den. (2025) Statistical Information Communication: past insights, future innovations. New Techniques and Technologies for Statistics (NTTS) 2025 conference, Brussels, Belgium. [(paper)](downloads/publications/NTTS2025_Stoel_etal.pdf)</span>

## 2024

<span class = "paper">Zhang, Z., Tennekes, M. De Jong, T. J. A., Curier, L., Coecke, B, Chen, M. (2024) Simulation-based optimization of user interfaces for quality-assuring machine learning model predictions. ACM Transactions on Interactive Intelligent Systems 14 (1), 1-32. [(paper)](https://arxiv.org/pdf/2104.01129)</span>

<span class = "paper">Canlon, D. C., Paulovich, F., Tennekes, M. (2024) FR-glyphs for Multidimensional Categorical Data. In EuroVis 2024 (Short Papers). The Eurographics Association. [(paper)](https://diglib.eg.org/server/api/core/bitstreams/af3180c7-7811-4f23-9107-f40896b81166/content)</span>

## 2023

<span class = "paper">Jin, Y, De Jong, T. J. A., Tennekes, M., Chen, M. (2023) Radial Icicle Tree (RIT): Node Separation and Area Constancy. IEEE Transactions on Visualization and Computer Graphics 30 (1), 251-261. [(paper)](https://arxiv.org/pdf/2307.10481)</span>

<span class = "paper">Tennekes, M. and Puts, M. J. H. (2023) cols4all: a color palette analysis tool. In EuroVis 2023 (Short Papers). The Eurographics Association. [(paper)](https://diglib.eg.org/server/api/core/bitstreams/74a93b33-066d-4826-92fb-169df2167d9d/content)</span>

<span class = "rep">Tennekes, M., Jonge, E. de, Puts, M. J. H., Meertens, V., Stoel. R. (2023) Visualization and communication of statistics. New Techniques and Technologies for Statistics (NTTS) 2023 conference, Brussels, Belgium. [(paper)](downloads/publications/NTTS2023_Tennekes_etal.pdf)</span>


## 2022

<span class = "paper">Tennekes, M., Gootzen, Y.A.P.M. (2022) Bayesian location estimation of mobile devices using a signal strength model. Journal of Spatial Information Science 25 (25), 29-66. [(paper)](https://josis.org/index.php/josis/article/download/166/169/877)</span>

<span class = "paper">Lovelace, R., Tennekes, M. Carlino, D. (2022) ClockBoard: a zoning system for urban analysis. Journal of Spatial Information Science 24 (24), 63-85. [(paper)](https://josis.org/index.php/josis/article/download/172/165/749)</span>

<span class = "rep">Daas, P.J.H., Tennekes, M., Miguel, B. de, Miguel Molina, M. de, Santamarina-Campos, V., Carausu, F. (2022) Web intelligence for measuring emerging economic trends: the drone industry. Publications Office of the European Union[(report)](https://www.researchgate.net/profile/Maria-De-Miguel-Molina/publication/361245478_Web_intelligence_for_measuring_emerging_economic_trends_the_drone_industry/links/62a5c43455273755ebe7a4e5/Web-intelligence-for-measuring-emerging-economic-trends-the-drone-industry.pdf)

## 2021

<span class = "paper">Tennekes, M. Chen, M. (2021) Design Space of Origin-Destination Data Visualization. Computer Graphics Forum 40(3), 323-334. [(paper)](http://diglib.eg.org/bitstream/handle/10.1111/cgf14310/v40i3pp323-334.pdf)[(appendix)](http://diglib.eg.org/bitstream/handle/10.1111/cgf14310/1047-file1.pdf)
[(presentation-short)](https://www.youtube.com/watch?v=yvRjvmkP_IQ)[(presentation-long)](https://youtu.be/BANTOSyWsFI)
</span>

<span class = "chapter">Daas, P.J.H., Schulte Nordholt, E., Tennekes, M., Ossen, S. (2021) Evaluation of the Quality of Administrative Data Used in the Dutch Virtual Census. In Young Chun, A. et al. (ed.) Administrative Records for Survey Methodology, 61-83. [(link)](https://www.wiley.com/en-us/Administrative+Records+for+Survey+Methodology-p-9781119272045)

<span class = "pres">Tennekes, M. Visualization of Mobility. Presentation at the seminar Big Data Matters 3 - The need for timely statistics. [(presentation)](https://www.cbs.nl/-/media/innovatie/big-data-matters-3-presentaties/tennekes_visualization-of-mobility---big-data-matters-3.pdf)[(video)](https://www.cbs.nl/bigdatamatters)

<span class = "soft">Lovelace, R., Tennekes, M. (2021) zonebuilder: Create and Explore Geographic Zoning Systems. [(R package version 0.0.1)](http://cran.r-project.org/package=zonebuilder) [(project home)](https://github.com/zonebuilders/zonebuilder)</span>

<span class = "soft">Tennekes, M. (2021) tmap: Thematic Maps. [(R package version 3.3-1)](http://cran.r-project.org/package=tmap) [(project home)](https://github.com/mtennekes/tmap)</span>

<span class = "soft">Tennekes, M. (2021) tmaptools: Thematic Maps Tools. [(R package version 3.1-1)](http://cran.r-project.org/package=tmaptools) [(project home)](https://github.com/mtennekes/tmaptools)</span>

<span class = "working">Zhang, Y., Tennekes, M. Jong, T.J.A., Curier, L., Coecke, B., Chen, M. Using Simulation to Aid the Design and Optimization of Intelligent User Interfaces for Quality Assurance Processes in Machine Learning. Working paper. [(paper)](https://arxiv.org/pdf/2104.01129)</span>

## 2020

<span class = "rep">Statistics Netherlands. (2020) Estimating hourly population flows in the Netherlands, Report, Statistics Netherlands, Heerlen, The Netherlands. [(paper)](https://www.cbs.nl/-/media/cbs/over-ons/innovatie/estimating-hourly-population-flows-in-the-netherlands.pdf)</span>

<span class = "pres">Tennekes, M. Visualization of origin-destination data
& a generic zoning system for cities. Presentation at the seminar Big Data Matters, Statistics Netherlands, Heerlen, The Netherlands. [(presentation)](downloads/presentations/Secondment_Martijn_Oxford.pdf)

<span class = "working">Tennekes, M., Gootzen, Y.A.P.M., Shah, S.H. A Bayesian approach to location estimation of mobile devices from mobile network operator data. CBDS Working Paper 06-20. [(paper)](https://www.cbs.nl/-/media/_pdf/2020/22/cbds_working_paper_location_estimation.pdf)</span>

<span class = "pres">Tennekes, M. Mapping human population. Seminars at University of London (City and King's College) and University of Leeds. [(presentation)](downloads/presentations/mapping_human_population.pdf)[(video)](https://mymedia.leeds.ac.uk/Mediasite/Showcase/default/Presentation/9cd108807cee4060b0509cef2d1346b71d/Desktop)</span>

## 2019

<span class = "pres">Tennekes, M. Creating thematic maps in R. Workshop at the OpenGeoHUB Summer School, Muenster, Germany. [(presentation)](downloads/presentations/tmap_opengeo_muenster.pdf)[(video)](https://www.youtube.com/watch?v=krcRR98C2Z0)</span>

<span class = "soft">Tennekes, M., Jonge, E. de (2019) tabplot: Tableplot, a visualization of large statistical datasets. [(project home)](https://github.com/mtennekes/tabplot)</span>

<span class = "pres">Ricciato, F., Wirthmann, A, Tennekes, M. Sakarovitch, B., Radini, R, Salgado, D. (2019) Towards a Reference Methodological Framework for processing Mobile Network Operator data for Official Statistics. Poster presented at the NetMob 2017 conference, Oxford, UK. [(abstract)](downloads/publications/netmob_v2.pdf) [(poster)](downloads/presentations/poster_netmob_RMF.pdf)</span>

<span class = "pres">Ponsen, M., Gootzen, Y., Puts, M. J. H., Tennekes, M., Jonge, E. de, Shah, S., Offermans, M. (2019) Towards Official Tourism Statistics - machine learning for processing signalling data. Poster presented at the NetMob 2019 conference, Oxford, UK. [(abstract)](downloads/publications/netmob19_paper_49.pdf) [(poster)](downloads/presentations/poster_netmob_Gootzen.pdf)</span>

<span class = "paper">Puts, M. J. H., Daas, P. J. H., Tennekes, M., Blois, C. de (2019) Using huge amounts of road sensor data for official statistics, AIMS Mathematics, 4(1), 12-25 [(link)](http://www.aimspress.com/article/10.3934/Math.2019.1.12/fulltext.html)</span>

## 2018

<span class = "rep">Tennekes, M. (2018) Aggregation of dots. Paper presented at the seminar Methods for Big Data in Official Statistics, Heerlen, The Netherlands. [(paper)](downloads/publications/Paper_M_Tennekes_Aggregation_of_dots.pdf) [(presentation)](downloads/presentations/methods_for_big_data_dotmap_2018.pdf)</span>

<span class = "rep">Meulemans, W., Tennekes, M. (2018) Assessing Dot-Map Aggregations. Poster paper presented at the IEEE VisWeek 2018. Berlin, Germany. [(paper)](downloads/publications/dotmapaggregation-visposter-2018.pdf)</span>


<span class = "rep">Salgado, D., Alexandru, C. Debusschere, M., Esteban, E., Nurmi, O., Oancea, B., Piela, P., Radini, R., Sakarovitch, B., Saldaña, S., Sanguiao, L., Tennekes, M., Williams, W., Zwick, M. (2018) Estimation of population counts combining official and mobile phone data. Paper for the European Conference on Quality in Official Statistics 2018, Krakow, Poland. [(paper)](downloads/publications/Session 32_David Salgado_paper.pdf)</span>

<span class = "rep">Salgado, D., Debusschere, M., Nurmi, O. Piela, P., Coudin, E., Sakarovitch, B., Hadam, S., Zwick, M., Radini, R., Tuoto, T., Tennekes, M., Alexandru, C., Oancea, B., Esteban, E., Saldaña, S., Sanguiao, L., Williams, W. (2018) ESSnet Big Data, WP5, Deliverable 5.3, Proposed Elements for a Methodological Framework for the 
Production of Official Statistics with Mobile Phone Data, Eurostat. [(report)](downloads/publications/WP5_Deliverable_5.3_Final.pdf)</span>

<span class = "rep">Salgado, D., Debusschere, M., Nurmi, O. Piela, P., Coudin, E., Sakarovitch, B., Hadam, S., Zwick, M., Radini, R., Tuoto, T., Tennekes, M., Alexandru, C., Oancea, B., Esteban, E., Saldaña, S., Sanguiao, L., Williams, W. (2018) ESSnet Big Data, WP5, Deliverable 5.4, Some IT elements for the use of mobile phone data in the production of official statistics, Eurostat. [(report)](downloads/publications/WP5_Deliverable_5.4_Final.pdf)</span>

<span class = "rep">Salgado, D., Debusschere, M., Nurmi, O. Piela, P., Coudin, E., Sakarovitch, B., Hadam, S., Zwick, M., Radini, R., Tuoto, T., Tennekes, M., Alexandru, C., Oancea, B., Esteban, E., Saldaña, S., Sanguiao, L., Williams, W. (2018) ESSnet Big Data, WP5, Deliverable 5.5, Some Quality Aspects and Future Prospects for the Production of Official Statistics with Mobile Phone Data, Eurostat. [(report)](downloads/publications/WP5_Deliverable_5.5_Final.pdf)</span>

<span class = "paper">Tennekes, M. (2018) tmap: Thematic Maps in R, Journal of Statistical Software, 84(6), 1-39 [(link)](https://doi.org/10.18637/jss.v084.i06)</span>

## 2017
	
<span class = "rep">Daas, P., Abbott, O., Alexandru, C., Bisioti, E., Chavdarov, V., Debusschere, M., Horvat, V., Museux, J-M., Reis, F., Ilves, M., Langsrud, O., Maslankowski, J., Portugal, A., Puts, M., Tennekes, M., Sanguiao, L., Six, M., Wu, D. (2017) Results of Workshop on: Important topics in the area of methodology, quality and IT when using big data for official statistics. Workpackage 8, ESSnet Big Data, Heerlen, The Netherlands. Version 19 June 2017. [(report)](downloads/publications/WP8_2017_04_25-26_Heerlen_Workshop_Report.pdf)</span>

<span class = "pres">Tennekes, M. Exploring and presenting maps with tmap. Presentation for the R User Conference (useR) 2017, Brussels, Belgium. [(abstract)](downloads/publications/abstract_tmap.pdf) [(presentation)](downloads/presentations/tmap_user2017.pdf)</span>

<span class = "rep">Tennekes, M., Offermans, M. Heerschap, N. (2017) Determining an optimal time window for roaming data for tourism statistics. Paper presented at the NetMob 2017 conference, Milan, Italy. [(paper)](downloads/publications/paper_netmob2017.pdf) [(poster)](downloads/presentations/Poster_netmob2017_v2.pdf)</span>

<span class = "rep">Tennekes, M., Jonge, E. de (2017) The compositional dot map: a visualization of spatial data. Paper presented at the 2017 New Techniques and Technologies for Statistics (NTTS) conference, Brussels, Belgium. [(extended abstract)](downloads/publications/The_compositional_dot_map_NTTS2017.pdf) [(presentation)](downloads/presentations/dotmap_NTTS.pdf)</span>

<span class = "soft">Tennekes, M. (2017) treemap: Treemap visualization. [(R package version 2.4-2)](http://cran.r-project.org/package=treemap) [(project home)](https://github.com/mtennekes/treemap)</span>

## 2016

<span class = "rep">Tennekes, M., Jonge, E. de (2016) Coloring interactive compositional dot maps. Poster paper presented at the 18th EG/VGTC Conference on Visualization (EuroVis 2016), Groningen, The Netherlands. [(paper)](downloads/publications/paper_dotmaps.pdf) [(presentation)](downloads/presentations/eurovis2016-FF-4Po06.pdf) [(poster)](downloads/presentations/poster_dotmaps.pdf)</span>

<span class = "rep">Puts, M., Tennekes, M., Daas, P.J.H., de Blois, C. (2016) Using huge amounts of road sensor data for official statistics. Paper and presentation for the European Conference on Quality in Official Statistics 2016, Madrid, Spain. [(paper)](downloads/publications/q2016Final00177.pdf) [(presentation)](downloads/presentations/Q2016_Q137.pdf)</span>

<span class = "pres">Tennekes, M. (2016) On the visualization of hierarchical, tabular and spatial data in R. Presentation for the New Challenges for Statistical Software - The Use of R in Official Statistics 2016, Bucharest, Romania. [(presentation)](downloads/presentations/presentation_TTT.pdf)</span>

	
## 2015
	
<span class = "pres">Tennekes, M. (2015) tmap: creating thematic maps in a flexible way. Presentation for the R User Conference 2015, Aalborg, Denmark. [(abstract)](downloads/publications/useR2015_tmap.pdf) [(presentation)](downloads/presentations/tmap_user2015.pdf)</span>

<span class = "pres">Tennekes, M. (2015) Data Visualization in Official Statistics. Presentation for invited workshop Data Meets Viz. University of Augsbourg, Germany. [(presentation)](downloads/presentations/DataVis_OfficialStatistics.pdf)</span>

<span class = "rep">Tennekes, M. (2015) High Frequency Road Sensor Data for Official Statistics. Paper presented at the 2015 New Techniques and Technologies for Statistics (NTTS) conference, Brussels, Belgium. [(paper)](downloads/publications/road_sensors1_NTTS2015.pdf) [(presentation)](downloads/presentations/road_sensors1_slides_NTTS2015.pdf) [(video, from 7:54:30 to 8:05:30)](https://scic.ec.europa.eu/streaming/index.php?es=2&sessionno=89d3d7800304002cd469f0c402bd3ea0)</span>

<span class = "rep">Tennekes, M., Puts, M. (2015) Projection of road sensors to the Dutch road network. Paper presented at the 2015 New Techniques and Technologies for Statistics (NTTS) conference, Brussels, Belgium. [(paper)](downloads/publications/road_sensors2_NTTS2015.pdf) [(presentation)](downloads/presentations/road_sensors2_slides_NTTS2015.pdf) [(video, from 8:05:30 to 8:15:35)](https://scic.ec.europa.eu/streaming/index.php?es=2&sessionno=89d3d7800304002cd469f0c402bd3ea0)</span>

<span class = "rep">Puts, M., Tennekes, M., Daas, P. (2014) Using Road Sensor Data for Official Statistics. Towards a Big Data Methodology. Presentation for the Strata + Hadoop World, organized by O'Reilly and Cloudera, Barcelona, Spain. [(abstract)](downloads/publications/Strata2014_RoadSensors_abstract.pdf) [(presentation)](downloads/presentations/Strata2014_RoadSensors.pdf)</span>
						
## 2014

<span class = "paper">Tennekes, M. Jonge, E. de (2014) Tree Colors: Color Schemes for Tree-Structured Data. IEEE Transactions on Visualization and Computer Graphics 20 (12), 2072 - 2081. [(paper)](downloads/publications/TreeColors_manuscript.pdf) [(video preview)](downloads/presentations/TreeColors_video_preview.mp4) [(fast forward presentation)](downloads/presentations/TreeColors_ff_pres.mp4) [(presentation)](downloads/presentations/TreeColors_pres.pdf)</span>

<span class = "pres">Offermans, M., Tennekes, M. (2014) Mobile Phone Metadata: A New Source for Official Statistics. Presentation for the 2014 Joint Statistical Meeting (JSM), Boston, USA. [(abstract)](http://www.amstat.org/meetings/jsm/2014/onlineprogram/AbstractDetails.cfm?abstractid=311965)</span>

<span class = "pres">Tennekes, M., Offermans, M. (2014) Daytime Population Estimations Based on Mobile Phone Metadata. Presentation for the 2014 Joint Statistical Meeting (JSM), Boston, USA. [(abstract)](http://www.amstat.org/meetings/jsm/2014/onlineprogram/AbstractDetails.cfm?abstractid=311959) [(presentation)](downloads/presentations/DTP_Martijn_Tennekes_JSM2014.pdf)</span>

<span class = "pres">Tennekes, M. (2014) Visualization and Big Data in Official Statistics. Presentation for the International Seminar on Big Data 2014, organized by Infotec, CIDE, and INEGI, Mexico City, Mexico. [(presentation)](downloads/presentations/BigData_Martijn_Tennekes_Mexico2014.pdf) [(video)](http://www.youtube.com/watch?v=t1To4I5oCrk)</span>

<span class = "rep">Braaksma, B., Daas, P., Offermans, M., Puts, M., Tennekes, M. (2014) Big Data and official statistics: local experiences and international initiatives, Proceedings of the 47th Scientific Meeting of the Italian Statistical Society (SIS), Cagliari, Italy. [(paper)](downloads/publications/SIS2014_Braaksma.pdf)</span>

## 2013

<span class = "rep">Tennekes,M., Jonge, E. de (2013) Poster: Hierarchical Qualitative Color Palettes. IEEE VisWeek 2013. Atlanta, USA. [(paper)](downloads/publications/hiercolor_infovis2013.pdf) [(poster)](downloads/presentations/poster_hiercols_infovis2013.pdf)</span>

<span class = "pres">Tennekes, M., Jonge, E. de (2013) Big data exploration with tabplot. Presentation for the R User Conference 2013, Albacete, Spain. [(abstract)](downloads/publications/useR2013_tabplot.pdf) [(presentation)](downloads/presentations/tabplot_user2013.pdf)</span>

<span class = "rep">Daas, P.J.H., Tennekes, M., Ossen, S., Di Bella, G., Galiè, L., Laitila, T., Lennartsson, D., Nilsson, R., Wallgren, A., Wallgren, B. (2013) Guidelines on the usage of the prototype of the computerized version of QRCA, and Report on the overall evaluation results. Second deliverable of workpackage 8 of the BLUE Enterprise and Trade Statistics project, March 29. [(paper)](downloads/publications/BLUE-ETS_WP8_Del2.pdf)</span>

<span class = "rep">Tennekes, M., Jonge, E. de (2013) On the exploration of high cardinality categorical data. Paper presented at the 2013 New Techniques and Technologies for Statistics (NTTS) conference, Brussels, Belgium. [(paper)](downloads/publications/NTTS-2013-Tableplot.pdf) [(presentation)](downloads/presentations/tableplot_NTTS2013.pdf)</span>

<span class = "paper">Tennekes, M., Jonge, E. de, Daas, P.J.H. (2013) Visualizing and Inspecting Large Datasets with Tableplots, Journal of Data Science 11 (1), 43-58. [(paper)](http://www.jds-online.com/file_download/379/JDS-1108.pdf)</span>

## 2012
<span class = "rep">Tennekes, M., Jonge, E. de, Daas, P.J.H. (2012) Innovative visual tools for data editing. Paper presented at the United Nations Economic Commission for Europe (UNECE) Work Session on Statistical Data Editing, 2012, Oslo, Norway. [(paper)](http://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.44/2012/30_Netherlands.pdf) [(presentation)](downloads/presentations/innovative_tools_CBS.pdf)</span>

<span class = "rep">Daas, P.J.H., Ossen, S.J.L., Tennekes, M., Burger, J. (2012) Evaluation and visualisation of the quality of administrative sources used for statistics. Paper for the European Conference on Quality in Official Statistics 2012, Athens, Greece. [(paper)](downloads/publications/Q2012_Session23_paper.pdf)</span>

<span class = "rep">Daas, P.J.H., Schulte Nordholt, E. with the cooperation of Jonge, E. de, Tennekes, M. (2012) Complete dataset kleurrijk weergeven in één figuur. E-data &amp; Research 6 (4), 7. [(paper)](downloads/publications/Tableplots_edata.pdf)</span>

## 2011

<span class = "rep">Daas, P.J.H., Ossen, S., Tennekes, M., Zhang, L-C., Hendriks, C., Foldal Haugen, K., Cerroni, F., Di Bella, G., Laitila, T., Wallgren, A., Wallgren, B. (2011) Report on methods preferred for the quality indicators of administrative data sources. Second deliverable of workpackage 4 of the BLUE Enterprise and Trade Statistics project, September 28. [(paper)](downloads/publications/BLUE-ETS_WP4_Del2.pdf)</span>

<span class = "rep">Ossen, S., Daas, P.J.H., Tennekes, M. (2011) Overall Assessment of the Quality of Administrative Data Sources. Proceedings of the 58th World Statistics Congress of the International Statistical Institute (ISI), Dublin, Ireland. [(paper)](downloads/publications/Paper_ISI2011.pdf) [(poster)](downloads/presentations/Poster_ISI2011.pdf)</span>

<span class = "rep">Daas, P.J.H., Ossen, S., Tennekes, M., Zhang, L-C., Hendriks, C., Foldal Haugen, K., Bernardi, A., Cerroni, F., Laitila, T., Wallgren, A., Wallgren, B. (2011) List of quality groups and indicators identified for administrative data sources. First deliverable of workpackage 4 of the BLUE Enterprise and Trade Statistics project, March 10. [(paper)](downloads/publications/BLUE-ETS_WP4_Del1.pdf)</span>

<span class = "rep">Tennekes, M., Jonge, E. de, Daas, P.J.H. (2011) Visual profiling of large statistical datasets. Paper presented at the 2011 New Techniques and Technologies for Statistics conference, Brussels, Belgium. [(paper)](downloads/publications/Tableplots.pdf) [(presentation)](downloads/presentations/NTTS_tableplots.pdf)</span>

<span class = "rep">Tennekes, M., Jonge, E. de (2011) Top-down data analysis with treemaps. Proceedings of the International Conference on Information Visualization Theory and Applications, IVAPP 2011, Algarve, Portugal. [(paper)](downloads/publications/Top-down_data_analysis_with_Treemaps.pdf) [(presentation)](downloads/presentations/IVAPP_treemaps.pdf)</span>

<span class = "paper">Derks, J.J.M. and Tennekes, M. (2011) Payoff functions in the one-way flow model of network formation for which Nash networks exist. International Game Theory Review 13 (1), 61-73. [(paper)](http://www.worldscientific.com/doi/pdf/10.1142/S0219198911002848)</span>

## 2010

<span class = "rep">Tennekes, M., Jonge, E. de (2010) Poster: Application of Treemaps to Business Statistics Analysis. IEEE VisWeek 2010. Salt Lake City, USA. [(paper)](downloads/publications/poster_paper_infovis2010.pdf) [(poster)](downloads/presentations/Poster_Treemaps.pdf)</span>

<span class = "rep">Daas, P.J.H., Ossen, S., Tennekes, M. (2010) Het meten van de kwaliteit van administratieve bronnen: recente resultaten en toekomstige ontwikkelingen. In: Bakker, B.F.M., Kuijvenhoven, L. (eds), Registers in sociaalwetenschappelijk onderzoek, Statistics Netherlands, VU University Amsterdam. [(paper)](downloads/publications/Bakker1.pdf)</span>

<span class = "rep">Daas, P.J.H., Ossen, S., Tennekes, M. (2010) Determination of administrative data quality: recent results and new developments. Proceedings of Q2010 European Conference on Quality in Official Statistics, Statistics Finland and Eurostat, Helsinki, Finland. [(paper)](downloads/publications/Q2010_Session34.pdf)</span>

## 2009

<span class = "paper">Tennekes, M. (2009) Network formation games. Dissertation. [(thesis)](downloads/publications/Thesis-Martijn_Tennekes.pdf) [(statements, in Dutch)](downloads/publications/Stellingen-Martijn_Tennekes.pdf) [(PhD defense presentation slides, in Dutch)](downloads/presentations/verdediging.pdf)</span>

<span class = "paper">Derks, J.J.M. and Tennekes, M. (2009) A note on the existence of Nash networks in one-way flow models. Economic Theory 41 (3), 515-522. [(link)](http://link.springer.com/article/10.1007%2Fs00199-008-0409-x)</span>

<span class = "paper">Derks, J.J.M., Kuipers, J.,Tennekes, M., and Thuijsman, F. (2009) Existence of Nash networks in the one-way flow model of network formation. In Neogy S. K. et al. (eds.), Modeling, Computation and Optimization, World Scientific, Ch 2. [(paper)](downloads/publications/Nash_networks.pdf)</span>

## 2008

<span class = "rep">Derks, J., Kuipers, J., Tennekes, M. (2008) An axiomatic approach covering the two-way flow model of network formation. Technical report, Maastricht University, Department of Mathematics. [(paper)](downloads/publications/twflow.pdf)</span>

<span class = "rep">Derks, J.J.M., Kuipers, J.,Tennekes, M., and Thuijsman, F. (2008) Local dynamics in network formation. Technical report, Maastricht University, Department of Mathematics. [(paper)](downloads/publications/localnet_okt-2008.pdf)</span>

:::